spring:
  application:
    name: backend
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:7878}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nota-music}
  jpa:
    hibernate:
      ddl-auto: create-drop