name: Build and Deploy Nota Music

on:
  push:
    branches:
      - dev

jobs:
  build-backend:
    name: Build Spring Boot Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: ''

      - name: Build backend
        run: |
          cd backend
          mvn clean package

      - name: Copy backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/target/*.jar

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Copy frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

  deploy:
    name: Deploy to Server via SSH
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: backend-jar
          path: backend/

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: frontend/

      - name: Copy files to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs:
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          port: 22
          script: |
            mkdir -p ~/music-app/backend ~/music-app/frontend ~/music-app

            cp ./backend/*.jar ~/music-app/backend/app.jar

            cp -r ./frontend/* ~/music-app/frontend/

            cp ./backend/Dockerfile ~/music-app/backend/
            cp ./frontend/Dockerfile ~/music-app/frontend/
            cp ./docker-compose.yml ~/music-app/

            cat <<EOF > ~/music-app/.env
            POSTGRES_USER=${POSTGRES_USER}
            POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            POSTGRES_DB=${POSTGRES_DB}
            EOF

            cd ~/music-app
            docker-compose down || true
            docker-compose --env-file .env up -d --build

            rm -rf ~/music-app/backend/*.jar ~/music-app/frontend/*